---
name: Latest Components

on:
  push:
    branches: [ feature/latest ]
  schedule:
    - cron:  '0 0 1,15 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -qr tests/resources/requirements-latest.txt
          pip freeze

      - name: Build
        run: echo $GITHUB_EVENT_NAME && make build

      - name: Test
        run: make test
